/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Smoggybeard (https://sketchfab.com/Smoggybeard)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solar-system-model-orrery-ca0a6f6971a94fcc8d47421342dc6f40
Title: Solar System Model (Orrery)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[-0.001, 0.295, -0.295]} rotation={[-Math.PI, 0, 0]} scale={0.571}>
          <group name="ee3f808601fd451d984787d7209dc68cfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Orerry_Rigged" position={[0, -81.972, 0]}>
                  <group name="Orerry_Bones" position={[0, 81.972, -0.924]}>
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <group name="Object_28" position={[0, -81.972, 0]} />
                      <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Orrery_Textures} skeleton={nodes.Object_29.skeleton} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
